// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGHGELwaHd2FVjl29SdOEOb8cY2K4bCt4',
    appId: '1:943930029724:web:42a23bdc9ac862f167df59',
    messagingSenderId: '943930029724',
    projectId: 'loveyourpet-c109b',
    authDomain: 'loveyourpet-c109b.firebaseapp.com',
    databaseURL: 'https://loveyourpet-c109b-default-rtdb.firebaseio.com',
    storageBucket: 'loveyourpet-c109b.appspot.com',
    measurementId: 'G-ME3PXXMZQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-GZGGoMKuSYyyUG7tIYUd82pWaYLNzE',
    appId: '1:943930029724:android:b67ee9f0b4abf69a67df59',
    messagingSenderId: '943930029724',
    projectId: 'loveyourpet-c109b',
    databaseURL: 'https://loveyourpet-c109b-default-rtdb.firebaseio.com',
    storageBucket: 'loveyourpet-c109b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9msRokqKaeEd976VSNFqZxSbnFgDsHfc',
    appId: '1:943930029724:ios:749ea6bed7123efc67df59',
    messagingSenderId: '943930029724',
    projectId: 'loveyourpet-c109b',
    databaseURL: 'https://loveyourpet-c109b-default-rtdb.firebaseio.com',
    storageBucket: 'loveyourpet-c109b.appspot.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9msRokqKaeEd976VSNFqZxSbnFgDsHfc',
    appId: '1:943930029724:ios:e5f43e1dfa0c67c567df59',
    messagingSenderId: '943930029724',
    projectId: 'loveyourpet-c109b',
    databaseURL: 'https://loveyourpet-c109b-default-rtdb.firebaseio.com',
    storageBucket: 'loveyourpet-c109b.appspot.com',
    iosBundleId: 'com.example.petCare.RunnerTests',
  );
}
